<?php

declare(strict_types=1);

return [

    'preset' => 'space',

    'drafts' => [

        draft('Country')
            ->set('table', 'country')
            ->set('endpoint', 'country')
            ->attribute()->id()->docs('ID')->example(1)
            ->attribute()->string('name')->fillable()->required()->min(3)->max(50)->faker('country')->docs('Nome')->example('Brasil')
            ->attribute()->integer('ibge_code')->fillable()->size(8)->nullable()->unique()->faker('numerify', '########')->docs('Código IBGE')->example(12345678)
            ->attribute()->timestamps()
            ->attribute()->softDeletes()
            ->relation()->hasMany('State')
            ->draft()
            ->push('generate', 'model')
            ->push('generate', 'migration:create')
            ->push('generate', 'migration:foreign')
            ->push('generate', 'factory')
            ->push('generate', 'controller:orion')
            ->push('generate', 'request:orion')
            ->push('generate', 'tester')
            ->push('generate', 'route:orion')
            ->data(),

        draft('State')
            ->set('table', 'state')
            ->set('endpoint', 'state')
            ->attribute()->id()->docs('ID')->example(1)
            ->attribute()->foreign('country_id')->fillable()->factory('Country')->docs('ID do país')->example(1)
            ->attribute()->string('name')->fillable()->required()->min(3)->max(50)->index()->faker('colorName')->docs('Nome')->example('Rio Grade do Sul')
            ->attribute()->string('abbreviation')->fillable()->required()->min(1)->max(5)->nullable()->faker('lexify', '##')->docs('Sigla')->example('RS')
            ->attribute()->integer('ibge_code')->fillable()->size(8)->nullable()->unique()->faker('numerify', '########')->docs('Código IBGE')->example(11223344)
            ->attribute()->timestamps()
            ->attribute()->softDeletes()
            ->relation()->belongsTo('Country')
            ->relation()->hasMany('City')
            ->draft()
            ->push('generate', 'model')
            ->push('generate', 'migration:create')
            ->push('generate', 'migration:foreign')
            ->push('generate', 'factory')
            ->push('generate', 'controller:orion')
            ->push('generate', 'request:orion')
            ->push('generate', 'tester')
            ->push('generate', 'route:orion')
            ->data(),

        draft('City')
            ->set('table', 'city')
            ->set('endpoint', 'city')
            ->attribute()->id()->docs('ID')->example(1)
            ->attribute()->foreign('state_id')->fillable()->factory('State')->docs('ID do estado')->example(1)
            ->attribute()->string('name')->fillable()->required()->min(3)->max(50)->faker('city')->docs('Nome')->example('Porto Alegre')
            ->attribute()->integer('ibge_code')->fillable()->size(8)->nullable()->unique()->faker('numerify', '########')->docs('Código IBGE')->example(12345678)
            ->attribute()->timestamps()
            ->attribute()->softDeletes()
            ->relation()->belongsTo('State')
            ->relation()->hasMany('Place')
            ->draft()
            ->push('generate', 'model')
            ->push('generate', 'migration:create')
            ->push('generate', 'migration:foreign')
            ->push('generate', 'factory')
            ->push('generate', 'controller:orion')
            ->push('generate', 'request:orion')
            ->push('generate', 'tester')
            ->push('generate', 'route:orion')
            ->data(),

        draft('Place')
            ->set('table', 'place')
            ->set('endpoint', 'place')
            ->attribute()->id()->docs('ID')->example(1)
            ->attribute()->foreign('city_id')->fillable()->factory('City')->docs('ID da cidade')->example(1)
            ->attribute()->string('address')->fillable()->required()->min(3)->max(200)->nullable()->faker('address')->docs('Endereço')->example('Rua do Centro')
            ->attribute()->string('number')->fillable()->nullable()->faker('numerify', '########')->docs('Número')->example(123)
            ->attribute()->string('complement')->fillable()->nullable()->faker('numerify', '########')->docs('Complemento')->example('Sala')
            ->attribute()->string('neighborhood')->fillable()->nullable()->faker('numerify', '########')->docs('Bairro')->example('Centro')
            ->attribute()->string('postal_code')->fillable()->nullable()->faker('numerify', '########')->docs('CEP')->example('12345-000')
            ->attribute()->float('latitude')->fillable()->nullable()->faker('latitude')->docs('Latitude')->example(0)
            ->attribute()->float('longitude')->fillable()->nullable()->faker('longitude')->docs('Longitude')->example(0)
            ->attribute()->timestamps()
            ->attribute()->softDeletes()
            ->relation()->belongsTo('City')
            ->draft()
            ->push('generate', 'model')
            ->push('generate', 'migration:create')
            ->push('generate', 'migration:foreign')
            ->push('generate', 'factory')
            ->push('generate', 'controller:orion')
            ->push('generate', 'request:orion')
            ->push('generate', 'tester')
            ->push('generate', 'route:orion')
            ->data(),

        draft('District')
            ->set('table', 'district')
            ->set('endpoint', 'district')
            ->attribute()->id()->docs('ID')->example(1)
            ->attribute()->foreign('city_id')->fillable()->factory('City')->docs('ID da cidade')->example(1)
            ->attribute()->string('name')->fillable()->required()->min(3)->max(50)->faker('city')->docs('Nome')->example('Centro')
            ->attribute()->integer('ibge_code')->fillable()->size(8)->nullable()->unique()->faker('numerify', '########')->docs('Código IBGE')->example(1234567890)
            ->attribute()->timestamps()
            ->attribute()->softDeletes()
            ->relation()->belongsTo('City')
            ->draft()
            ->push('generate', 'model')
            ->push('generate', 'migration:create')
            ->push('generate', 'migration:foreign')
            ->push('generate', 'factory')
            ->push('generate', 'controller:orion')
            ->push('generate', 'request:orion')
            ->push('generate', 'tester')
            ->push('generate', 'route:orion')
            ->data(),

    ],

];
